-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Igrac"
(
    id_igraca integer NOT NULL,
    ime character varying(128) COLLATE pg_catalog."default" NOT NULL,
    prezime character varying(128) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Igrač_pkey" PRIMARY KEY (id_igraca)
);

CREATE TABLE IF NOT EXISTS public."Mec"
(
    id_meca integer NOT NULL,
    broj_terena integer NOT NULL,
    vrijeme_igre integer NOT NULL,
    datum_meca date NOT NULL,
    stadij character varying(128) COLLATE pg_catalog."default" NOT NULL,
    ime_turnira character varying(128) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Meč_pkey" PRIMARY KEY (id_meca)
);

CREATE TABLE IF NOT EXISTS public."MecIgrac"
(
    id_meca integer NOT NULL,
    id_igraca integer NOT NULL,
    osvojeni_setovi integer NOT NULL,
    osvojeni_poeni integer NOT NULL,
    as_servisi integer NOT NULL,
    forsirane_greske integer NOT NULL,
    neforsirane_greske integer NOT NULL,
    uspjesni_servisi integer NOT NULL,
    neuspjesni_servisi integer NOT NULL,
    izlasci_na_mrezu integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."MecSudac"
(
    id_meca integer NOT NULL,
    id_suca integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Sudac"
(
    id_suca integer NOT NULL,
    ime character varying(128) COLLATE pg_catalog."default" NOT NULL,
    prezime character varying(128) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Sudac_pkey" PRIMARY KEY (id_suca)
);

CREATE TABLE IF NOT EXISTS public."Turnir"
(
    ime_turnira character varying(128) COLLATE pg_catalog."default" NOT NULL,
    datum_pocetka date NOT NULL,
    CONSTRAINT "Turnir_pkey" PRIMARY KEY (ime_turnira)
);

CREATE TABLE IF NOT EXISTS public."TurnirIgrac"
(
    "id_igrača" integer NOT NULL,
    ime_turnira character varying(128) COLLATE pg_catalog."default" NOT NULL
);